[project]
name = "animation"
version = "0.1.0"
description = "create animations for our video"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.0",
    "pip>=25.0.1",
]
